## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
cutoff_value = 550
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts = application_df['CLASSIFICATION'].value_counts()
class_count_1 = class_counts[class_counts > 1]
class_count_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
cutoff_value_class = 1883
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies = pd.get_dummies(application_df)
dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
y = dummies['IS_SUCCESSFUL']
X = dummies.drop(['IS_SUCCESSFUL'], axis=1)
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train.columns)
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=10, input_dim=input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                440

 dense_1 (Dense)             (None, 5)                 55

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 501 (1.96 KB)
Trainable params: 501 (1.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Train the model
history = nn.fit(X_train, y_train, epochs=50, verbose=1, validation_data=(X_test, y_test))

Epoch 1/50
804/804 [==============================] - 4s 5ms/step - loss: 15692.5596 - accuracy: 0.4979 - val_loss: 670.0010 - val_accuracy: 0.5343
Epoch 2/50
804/804 [==============================] - 6s 8ms/step - loss: 7250.2217 - accuracy: 0.5170 - val_loss: 480.6318 - val_accuracy: 0.5343
Epoch 3/50
804/804 [==============================] - 5s 6ms/step - loss: 12295.3086 - accuracy: 0.5050 - val_loss: 331.9071 - val_accuracy: 0.5179
Epoch 4/50
804/804 [==============================] - 4s 5ms/step - loss: 6934.0366 - accuracy: 0.5148 - val_loss: 1418.2512 - val_accuracy: 0.6217
Epoch 5/50
804/804 [==============================] - 5s 6ms/step - loss: 7228.1182 - accuracy: 0.5463 - val_loss: 2729.8923 - val_accuracy: 0.4657
Epoch 6/50
804/804 [==============================] - 4s 5ms/step - loss: 11542.8721 - accuracy: 0.5231 - val_loss: 67.5013 - val_accuracy: 0.5296
Epoch 7/50
804/804 [==============================] - 4s 5ms/step - loss: 4066.0605 - accuracy: 0.5351 - val_loss: 22124.0996 - val_accuracy: 0.4657
Epoch 8/50
804/804 [==============================] - 5s 6ms/step - loss: 11625.6367 - accuracy: 0.5144 - val_loss: 5827.7686 - val_accuracy: 0.4657
Epoch 9/50
804/804 [==============================] - 4s 5ms/step - loss: 10428.8184 - accuracy: 0.5173 - val_loss: 28.9679 - val_accuracy: 0.5343
Epoch 10/50
804/804 [==============================] - 4s 5ms/step - loss: 5967.2236 - accuracy: 0.5361 - val_loss: 3059.8198 - val_accuracy: 0.5343
Epoch 11/50
804/804 [==============================] - 4s 6ms/step - loss: 3305.7593 - accuracy: 0.5022 - val_loss: 15802.5176 - val_accuracy: 0.4657
Epoch 12/50
804/804 [==============================] - 5s 6ms/step - loss: 9288.4473 - accuracy: 0.5285 - val_loss: 54.6187 - val_accuracy: 0.5343
Epoch 13/50
804/804 [==============================] - 4s 5ms/step - loss: 4891.7056 - accuracy: 0.5439 - val_loss: 4408.7002 - val_accuracy: 0.4657
Epoch 14/50
804/804 [==============================] - 4s 6ms/step - loss: 4269.7588 - accuracy: 0.5309 - val_loss: 208.1127 - val_accuracy: 0.5445
Epoch 15/50
804/804 [==============================] - 4s 5ms/step - loss: 8247.9180 - accuracy: 0.5312 - val_loss: 6518.5068 - val_accuracy: 0.4657
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 8620.3359 - accuracy: 0.5105 - val_loss: 3020.6519 - val_accuracy: 0.4658
Epoch 17/50
804/804 [==============================] - 4s 5ms/step - loss: 3864.4922 - accuracy: 0.5416 - val_loss: 503.9778 - val_accuracy: 0.6167
Epoch 18/50
804/804 [==============================] - 4s 6ms/step - loss: 1499.1711 - accuracy: 0.5603 - val_loss: 10.2128 - val_accuracy: 0.5785
Epoch 19/50
804/804 [==============================] - 4s 4ms/step - loss: 2775.2856 - accuracy: 0.5526 - val_loss: 2947.3682 - val_accuracy: 0.4657
Epoch 20/50
804/804 [==============================] - 4s 5ms/step - loss: 8583.0859 - accuracy: 0.5170 - val_loss: 1978.6908 - val_accuracy: 0.5101
Epoch 21/50
804/804 [==============================] - 5s 6ms/step - loss: 5980.6401 - accuracy: 0.5225 - val_loss: 1226.5135 - val_accuracy: 0.5343
Epoch 22/50
804/804 [==============================] - 4s 4ms/step - loss: 1454.0876 - accuracy: 0.5542 - val_loss: 985.7895 - val_accuracy: 0.6603
Epoch 23/50
804/804 [==============================] - 4s 5ms/step - loss: 4256.3384 - accuracy: 0.5518 - val_loss: 1182.1416 - val_accuracy: 0.5343
Epoch 24/50
804/804 [==============================] - 5s 6ms/step - loss: 1875.3295 - accuracy: 0.5238 - val_loss: 5855.6484 - val_accuracy: 0.4657
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 1717.3873 - accuracy: 0.5479 - val_loss: 1932.2495 - val_accuracy: 0.4793
Epoch 26/50
804/804 [==============================] - 3s 4ms/step - loss: 2171.0469 - accuracy: 0.5310 - val_loss: 28.0803 - val_accuracy: 0.5353
Epoch 27/50
804/804 [==============================] - 4s 5ms/step - loss: 4033.8247 - accuracy: 0.5383 - val_loss: 828.1608 - val_accuracy: 0.6330
Epoch 28/50
804/804 [==============================] - 4s 5ms/step - loss: 3540.2275 - accuracy: 0.5243 - val_loss: 24.7632 - val_accuracy: 0.5343
Epoch 29/50
804/804 [==============================] - 3s 4ms/step - loss: 2455.0212 - accuracy: 0.5138 - val_loss: 26.5824 - val_accuracy: 0.5313
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 2078.7476 - accuracy: 0.5548 - val_loss: 941.0952 - val_accuracy: 0.5343
Epoch 31/50
804/804 [==============================] - 4s 6ms/step - loss: 1087.7025 - accuracy: 0.5381 - val_loss: 683.6093 - val_accuracy: 0.6099
Epoch 32/50
804/804 [==============================] - 3s 4ms/step - loss: 2200.0042 - accuracy: 0.5341 - val_loss: 242.4034 - val_accuracy: 0.5343
Epoch 33/50
804/804 [==============================] - 4s 5ms/step - loss: 991.3412 - accuracy: 0.5682 - val_loss: 9.2522 - val_accuracy: 0.5431
Epoch 34/50
804/804 [==============================] - 5s 6ms/step - loss: 984.6415 - accuracy: 0.5596 - val_loss: 2025.0186 - val_accuracy: 0.4657
Epoch 35/50
804/804 [==============================] - 3s 4ms/step - loss: 691.1384 - accuracy: 0.5306 - val_loss: 17.5609 - val_accuracy: 0.5343
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 121.2676 - accuracy: 0.5627 - val_loss: 155.8580 - val_accuracy: 0.5343
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 409.6360 - accuracy: 0.5417 - val_loss: 0.7003 - val_accuracy: 0.5343
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6961 - accuracy: 0.5318 - val_loss: 0.6922 - val_accuracy: 0.5343
Epoch 39/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6919 - accuracy: 0.5318 - val_loss: 0.6909 - val_accuracy: 0.5343
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 41/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 49/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343
Epoch 50/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5343

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 1.4377 - accuracy: 0.6987 - 584ms/epoch - 2ms/step
Loss: 1.4376670122146606, Accuracy: 0.6986588835716248

In [ ]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")